name: Docker Build and Push deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.run_number }}
      ECR_REPOSITORY: ref-ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

 
      - name: Push Docker image
        run: |
          echo "${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    env:
      IMAGE_TAG: ${{ needs.build-and-push.outputs.IMAGE_TAG }}
      ECR_REPOSITORY: ${{ needs.build-and-push.outputs.ECR_REPOSITORY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute SSH commmands on remote server[44.202.226.33]
        uses: appleboy/ssh-action@master
        with:
          host: 44.202.226.33
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD_01 }}
          port: 60022
          script: |
            echo "${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
