name: Docker Build and Push deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      id: build-and-push
      values:
        IMAGE_TAG: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Image Tag
        id: set-image-tag
        run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 046257248069.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t 046257248069.dkr.ecr.us-east-1.amazonaws.com/ref-ui:${{ needs.build-and-push.outputs.IMAGE_TAG }} .

      - name: Push Docker image
        run: |
          docker push 046257248069.dkr.ecr.us-east-1.amazonaws.com/ref-ui:${{ needs.build-and-push.outputs.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute SSH commands on remote server[44.202.226.33]
        uses: appleboy/ssh-action@master
        with:
          host: 44.202.226.33
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD_01 }}
          port: 60022
          script: |
            docker stop ref-ui || true
            docker rm ref-ui || true
            docker pull 046257248069.dkr.ecr.us-east-1.amazonaws.com/ref-ui:${{ needs.build-and-push.outputs.IMAGE_TAG }}
            timeout=300
            elapsed=0
            while ! docker pull 046257248069.dkr.ecr.us-east-1.amazonaws.com/ref-ui:${{ needs.build-and-push.outputs.IMAGE_TAG }} | grep -q "Image is up to date"; do
              sleep 10
              elapsed=$((elapsed+10))
              if [ "$elapsed" -ge "$timeout" ]; then
                echo "Timeout waiting for Docker pull."
                exit 1
              fi
            done
            docker run -d -p 8080:80 --name ref-ui 046257248069.dkr.ecr.us-east-1.amazonaws.com/ref-ui:${{ needs.build-and-push.outputs.IMAGE_TAG }}

      - name: Execute SSH commands on remote server[3.238.218.91]
        uses: appleboy/ssh-action@master
        with:
          host: 3.238.218.91
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD_02 }}
          port: 60022
          script: |
            docker stop ref-ui || true
            docker rm ref-ui || true
            docker pull 046257248069.dkr.ecr.us-east-1.amazonaws.com/ref-ui:${{ needs.build-and-push.outputs.IMAGE_TAG }}
            timeout=300
            elapsed=0
            while ! docker pull 046257248069.dkr.ecr.us-east-1.amazonaws.com/ref-ui:${{ needs.build-and-push.outputs.IMAGE_TAG }} | grep -q "Image is up to date"; do
              sleep 10
              elapsed=$((elapsed+10))
              if [ "$elapsed" -ge "$timeout" ]; then
                echo "Timeout waiting for Docker pull."
                exit 1
              fi
            done
            docker run -d -p 8080:80 --name ref-ui 046257248069.dkr.ecr.us-east-1.amazonaws.com/ref-ui:${{ needs.build-and-push.outputs.IMAGE_TAG }}
