name: Outputs Example

on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest

    outputs:
      # 在这里定义输出变量
      # 格式为输出名称: ${{ steps.<step-id>.outputs.<output-name> }}
      id: myoutputs
      outputs: [example_output]

    steps:
      - name: Set example output
        id: set_output
        run: echo "::set-output name=example_output::Hello from GitHub Actions!"

      - name: Use example output
        run: echo "Example output: ${{ needs.example.outputs.example_output }}"
